<a href="https://colab.research.google.com/github/NiyazovIlia/natural_language/blob/lesson_1/hw_lesson_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Осуществим предобработку данных с Твиттера, чтобы отчищенный данные в дальнейшем использовать для задачи классификации. Данный датасет содержит негативные (label = 1) и нейтральные (label = 0) высказывания.
Для работы объединим train_df и test_df.

Задания:

1) Удалим @user из всех твитов с помощью паттерна "@[\w]*". Для этого создадим функцию: 
 - для того, чтобы найти все вхождения паттерна в тексте, необходимо использовать re.findall(pattern, input_txt)
 - для для замены @user на пробел, необходимо использовать re.sub()

2) Изменим регистр твитов на нижний с помощью .lower().

3) Заменим сокращения с апострофами (пример: ain't, can't) на пробел, используя apostrophe_dict. Для этого необходимо сделать функцию: для каждого слова в тексте проверить (for word in text.split()), если слово есть в словаре apostrophe_dict в качестве ключа (сокращенного слова), то заменить ключ на значение (полную версию слова).

4) Заменим сокращения на их полные формы, используя short_word_dict. Для этого воспользуемся функцией, используемой в предыдущем пункте.

5) Заменим эмотиконы (пример: ":)" = "happy") на пробелы, используя emoticon_dict. Для этого воспользуемся функцией, используемой в предыдущем пункте.

6) Заменим пунктуацию на пробелы, используя re.sub() и паттерн r'[^\w\s]'.

7) Заменим спец. символы на пробелы, используя re.sub() и паттерн r'[^a-zA-Z0-9]'.

8) Заменим числа на пробелы, используя re.sub() и паттерн r'[^a-zA-Z]'.

9) Удалим из текста слова длиной в 1 символ, используя ' '.join([w for w in x.split() if len(w)>1]).

10) Поделим твиты на токены с помощью nltk.tokenize.word_tokenize, создав новый столбец 'tweet_token'.

11) Удалим стоп-слова из токенов, используя nltk.corpus.stopwords. Создадим столбец 'tweet_token_filtered' без стоп-слов.

12) Применим стемминг к токенам с помощью nltk.stem.PorterStemmer. Создадим столбец 'tweet_stemmed' после применения стемминга.

13) Применим лемматизацию к токенам с помощью nltk.stem.wordnet.WordNetLemmatizer. Создадим столбец 'tweet_lemmatized' после применения лемматизации.

14) Сохраним результат предобработки в pickle-файл.

In [1]:
apostrophe_dict = {
"ain't": "am not / are not",
"aren't": "are not / am not",
"can't": "cannot",
"can't've": "cannot have",
"'cause": "because",
"could've": "could have",
"couldn't": "could not",
"couldn't've": "could not have",
"didn't": "did not",
"doesn't": "does not",
"don't": "do not",
"hadn't": "had not",
"hadn't've": "had not have",
"hasn't": "has not",
"haven't": "have not",
"he'd": "he had / he would",
"he'd've": "he would have",
"he'll": "he shall / he will",
"he'll've": "he shall have / he will have",
"he's": "he has / he is",
"how'd": "how did",
"how'd'y": "how do you",
"how'll": "how will",
"how's": "how has / how is",
"i'd": "I had / I would",
"i'd've": "I would have",
"i'll": "I shall / I will",
"i'll've": "I shall have / I will have",
"i'm": "I am",
"i've": "I have",
"isn't": "is not",
"it'd": "it had / it would",
"it'd've": "it would have",
"it'll": "it shall / it will",
"it'll've": "it shall have / it will have",
"it's": "it has / it is",
"let's": "let us",
"ma'am": "madam",
"mayn't": "may not",
"might've": "might have",
"mightn't": "might not",
"mightn't've": "might not have",
"must've": "must have",
"mustn't": "must not",
"mustn't've": "must not have",
"needn't": "need not",
"needn't've": "need not have",
"o'clock": "of the clock",
"oughtn't": "ought not",
"oughtn't've": "ought not have",
"shan't": "shall not",
"sha'n't": "shall not",
"shan't've": "shall not have",
"she'd": "she had / she would",
"she'd've": "she would have",
"she'll": "she shall / she will",
"she'll've": "she shall have / she will have",
"she's": "she has / she is",
"should've": "should have",
"shouldn't": "should not",
"shouldn't've": "should not have",
"so've": "so have",
"so's": "so as / so is",
"that'd": "that would / that had",
"that'd've": "that would have",
"that's": "that has / that is",
"there'd": "there had / there would",
"there'd've": "there would have",
"there's": "there has / there is",
"they'd": "they had / they would",
"they'd've": "they would have",
"they'll": "they shall / they will",
"they'll've": "they shall have / they will have",
"they're": "they are",
"they've": "they have",
"to've": "to have",
"wasn't": "was not",
"we'd": "we had / we would",
"we'd've": "we would have",
"we'll": "we will",
"we'll've": "we will have",
"we're": "we are",
"we've": "we have",
"weren't": "were not",
"what'll": "what shall / what will",
"what'll've": "what shall have / what will have",
"what're": "what are",
"what's": "what has / what is",
"what've": "what have",
"when's": "when has / when is",
"when've": "when have",
"where'd": "where did",
"where's": "where has / where is",
"where've": "where have",
"who'll": "who shall / who will",
"who'll've": "who shall have / who will have",
"who's": "who has / who is",
"who've": "who have",
"why's": "why has / why is",
"why've": "why have",
"will've": "will have",
"won't": "will not",
"won't've": "will not have",
"would've": "would have",
"wouldn't": "would not",
"wouldn't've": "would not have",
"y'all": "you all",
"y'all'd": "you all would",
"y'all'd've": "you all would have",
"y'all're": "you all are",
"y'all've": "you all have",
"you'd": "you had / you would",
"you'd've": "you would have",
"you'll": "you shall / you will",
"you'll've": "you shall have / you will have",
"you're": "you are",
"you've": "you have"
}



short_word_dict = {
"121": "one to one",
"a/s/l": "age, sex, location",
"adn": "any day now",
"afaik": "as far as I know",
"afk": "away from keyboard",
"aight": "alright",
"alol": "actually laughing out loud",
"b4": "before",
"b4n": "bye for now",
"bak": "back at the keyboard",
"bf": "boyfriend",
"bff": "best friends forever",
"bfn": "bye for now",
"bg": "big grin",
"bta": "but then again",
"btw": "by the way",
"cid": "crying in disgrace",
"cnp": "continued in my next post",
"cp": "chat post",
"cu": "see you",
"cul": "see you later",
"cul8r": "see you later",
"cya": "bye",
"cyo": "see you online",
"dbau": "doing business as usual",
"fud": "fear, uncertainty, and doubt",
"fwiw": "for what it's worth",
"fyi": "for your information",
"g": "grin",
"g2g": "got to go",
"ga": "go ahead",
"gal": "get a life",
"gf": "girlfriend",
"gfn": "gone for now",
"gmbo": "giggling my butt off",
"gmta": "great minds think alike",
"h8": "hate",
"hagn": "have a good night",
"hdop": "help delete online predators",
"hhis": "hanging head in shame",
"iac": "in any case",
"ianal": "I am not a lawyer",
"ic": "I see",
"idk": "I don't know",
"imao": "in my arrogant opinion",
"imnsho": "in my not so humble opinion",
"imo": "in my opinion",
"iow": "in other words",
"ipn": "I’m posting naked",
"irl": "in real life",
"jk": "just kidding",
"l8r": "later",
"ld": "later, dude",
"ldr": "long distance relationship",
"llta": "lots and lots of thunderous applause",
"lmao": "laugh my ass off",
"lmirl": "let's meet in real life",
"lol": "laugh out loud",
"ltr": "longterm relationship",
"lulab": "love you like a brother",
"lulas": "love you like a sister",
"luv": "love",
"m/f": "male or female",
"m8": "mate",
"milf": "mother I would like to fuck",
"oll": "online love",
"omg": "oh my god",
"otoh": "on the other hand",
"pir": "parent in room",
"ppl": "people",
"r": "are",
"rofl": "roll on the floor laughing",
"rpg": "role playing games",
"ru": "are you",
"shid": "slaps head in disgust",
"somy": "sick of me yet",
"sot": "short of time",
"thanx": "thanks",
"thx": "thanks",
"ttyl": "talk to you later",
"u": "you",
"ur": "you are",
"uw": "you’re welcome",
"wb": "welcome back",
"wfm": "works for me",
"wibni": "wouldn't it be nice if",
"wtf": "what the fuck",
"wtg": "way to go",
"wtgp": "want to go private",
"ym": "young man",
"gr8": "great"
}


emoticon_dict = {
":)": "happy",
":‑)": "happy",
":-]": "happy",
":-3": "happy",
":->": "happy",
"8-)": "happy",
":-}": "happy",
":o)": "happy",
":c)": "happy",
":^)": "happy",
"=]": "happy",
"=)": "happy",
"<3": "happy",
":-(": "sad",
":(": "sad",
":c": "sad",
":<": "sad",
":[": "sad",
">:[": "sad",
":{": "sad",
">:(": "sad",
":-c": "sad",
":-< ": "sad",
":-[": "sad",
":-||": "sad"
}

In [2]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
import warnings 
warnings.filterwarnings("ignore", category=DeprecationWarning)
import os
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk import tokenize as tknz
nltk.download('punkt')
from nltk.corpus import stopwords
nltk.download('stopwords')
import pickle

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [3]:
train_df = pd.read_csv('train_tweets.csv')
train_df.head()

   id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

In [4]:
test_df = pd.read_csv('test_tweets.csv')
test_df.head()

      id                                              tweet
0  31963  #studiolife #aislife #requires #passion #dedic...
1  31964   @user #white #supremacists want everyone to s...
2  31965  safe ways to heal your #acne!!    #altwaystohe...
3  31966  is the hp and the cursed child book up for res...
4  31967    3rd #bihday to my amazing, hilarious #nephew...

In [5]:
combine_df = train_df.append(test_df, ignore_index = True, sort = False)
combine_df.head()

   id  label                                              tweet
0   1    0.0   @user when a father is dysfunctional and is s...
1   2    0.0  @user @user thanks for #lyft credit i can't us...
2   3    0.0                                bihday your majesty
3   4    0.0  #model   i love u take with u all the time in ...
4   5    0.0             factsguide: society now    #motivation

In [6]:
print(combine_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49159 entries, 0 to 49158
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      49159 non-null  int64
 1   label   31962 non-null  float64
 2   tweet   49159 non-null  object
dtypes: float64(1), int64(1), object(1)
memory usage: 1.1+ MB
None

1. Удалим @user из всех твитов с помощью паттерна "@[\w]*". Для этого создадим функцию: 
 - для того, чтобы найти все вхождения паттерна в тексте, необходимо использовать re.findall(pattern, input_txt)
 - для для замены @user на пробел, необходимо использовать re.sub()

In [7]:
def delete_user(text):
    try:
        return re.sub(r'@[\w]*', ' ', text)
    except:
        return []

In [8]:
train_df['tweet'] = train_df['tweet'].apply(delete_user)
test_df['tweet'] = test_df['tweet'].apply(delete_user)
combine_df['tweet'] = combine_df['tweet'].apply(delete_user)

2. Изменим регистр твитов на нижний с помощью .lower()

In [9]:
def lower_test(text):
    try:
        return text.lower()
    except:
        return []

In [10]:
train_df['tweet'] = train_df['tweet'].apply(lower_test)
test_df['tweet'] = test_df['tweet'].apply(lower_test)
combine_df['tweet'] = combine_df['tweet'].apply(lower_test)

3. Заменим сокращения с апострофами (пример: ain't, can't) на пробел, используя apostrophe_dict. Для этого необходимо сделать функцию: для каждого слова в тексте проверить (for word in text.split()), если слово есть в словаре apostrophe_dict в качестве ключа (сокращенного слова), то заменить ключ на значение (полную версию слова).

In [11]:
def replace_abbreviations(text):
  for word in text.split():
    for key, value in apostrophe_dict.items():
      if word == key:
        text = re.sub(rf"\s{word}\s", f' {value} ', text)
  return text

In [12]:
train_df['tweet'] = train_df['tweet'].apply(replace_abbreviations)
test_df['tweet'] = test_df['tweet'].apply(replace_abbreviations)
combine_df['tweet'] = combine_df['tweet'].apply(replace_abbreviations)

4. Заменим сокращения на их полные формы, используя short_word_dict. Для этого воспользуемся функцией, используемой в предыдущем пункте.

In [13]:
def replace_short(text):
  for word in text.split():
    for key, value in short_word_dict.items():
      if word == key:
        text = re.sub(rf"\s{word}\s", f' {value} ', text)
  return text

In [14]:
train_df['tweet'] = train_df['tweet'].apply(replace_short)
test_df['tweet'] = test_df['tweet'].apply(replace_short)
combine_df['tweet'] = combine_df['tweet'].apply(replace_short)

5. Заменим эмотиконы (пример: ":)" = "happy") на пробелы, используя emoticon_dict. Для этого воспользуемся функцией, используемой в предыдущем пункте.

In [15]:
def replace_emoticon(text):
  for word in text.split():
    for key, value in emoticon_dict.items():
      if word == key:
        text = text.replace(word, value)
  return text

In [16]:
train_df['tweet'] = train_df['tweet'].apply(replace_emoticon)
test_df['tweet'] = test_df['tweet'].apply(replace_emoticon)
combine_df['tweet'] = combine_df['tweet'].apply(replace_emoticon)

6. Заменим пунктуацию на пробелы, используя re.sub() и паттерн r'[^\w\s]'

In [17]:
def punctuation(text):
    try:
        return re.sub(r'[^\w\s]', ' ', text)
    except:
        return []

In [18]:
train_df['tweet'] = train_df['tweet'].apply(punctuation)
test_df['tweet'] = test_df['tweet'].apply(punctuation)
combine_df['tweet'] = combine_df['tweet'].apply(punctuation)

7. Заменим спец. символы на пробелы, используя re.sub() и паттерн r'[^a-zA-Z0-9]'

In [19]:
def special_characters(text):
    try:
        return re.sub(r'[^a-zA-Z0-9]', ' ', text)
    except:
        return []

In [20]:
train_df['tweet'] = train_df['tweet'].apply(special_characters)
test_df['tweet'] = test_df['tweet'].apply(special_characters)
combine_df['tweet'] = combine_df['tweet'].apply(special_characters)

8. Заменим числа на пробелы, используя re.sub() и паттерн r'[^a-zA-Z]'

In [21]:
def delete_numbers(text):
    try:
        return re.sub(r'[^a-zA-Z]', ' ', text)
    except:
        return []

In [22]:
train_df['tweet'] = train_df['tweet'].apply(delete_numbers)
test_df['tweet'] = test_df['tweet'].apply(delete_numbers)
combine_df['tweet'] = combine_df['tweet'].apply(delete_numbers)

9. Удалим из текста слова длиной в 1 символ, используя ' '.join([w for w in x.split() if len(w)>1])

In [23]:
def delete_symbol(text):
  try:
    return ' '.join([w for w in text.split() if len(w)>1])
  except:
    return []

In [24]:
train_df['tweet'] = train_df['tweet'].apply(delete_symbol)
test_df['tweet'] = test_df['tweet'].apply(delete_symbol)
combine_df['tweet'] = combine_df['tweet'].apply(delete_symbol)

10. Поделим твиты на токены с помощью nltk.tokenize.word_tokenize, создав новый столбец 'tweet_token'.

In [25]:
def word_token(text):
  try:
    return tknz.word_tokenize(text)
  except:
    return []

In [26]:
train_df['tweet_token'] = train_df['tweet'].apply(word_token)
test_df['tweet_token'] = test_df['tweet'].apply(word_token)
combine_df['tweet_token'] = combine_df['tweet'].apply(word_token)

11. Удалим стоп-слова из токенов, используя nltk.corpus.stopwords. Создадим столбец 'tweet_token_filtered' без стоп-слов.

In [27]:
def delete_stop_words(text):
  stop_words = set(stopwords.words("english"))
  without_stop_words = [word for word in text if not word in stop_words]
  try:
    return without_stop_words
  except:
    return []

In [28]:
train_df['tweet_token_filtered'] = train_df['tweet_token'].apply(delete_stop_words)
test_df['tweet_token_filtered'] = test_df['tweet_token'].apply(delete_stop_words)
combine_df['tweet_token_filtered'] = combine_df['tweet_token'].apply(delete_stop_words)

12. Применим стемминг к токенам с помощью nltk.stem.PorterStemmer. Создадим столбец 'tweet_stemmed' после применения стемминга.

In [29]:
def stems(text):
  stemmer = PorterStemmer()
  test = []
  for i in text:
    test.append(stemmer.stem(i))
  return test

In [30]:
train_df['tweet_stemmed'] = train_df['tweet_token_filtered'].apply(stems)
test_df['tweet_stemmed'] = test_df['tweet_token_filtered'].apply(stems)
combine_df['tweet_stemmed'] = combine_df['tweet_token_filtered'].apply(stems)

13. Применим лемматизацию к токенам с помощью nltk.stem.wordnet.WordNetLemmatizer. Создадим столбец 'tweet_lemmatized' после применения лемматизации.

In [31]:
def lems(text):
  stemmer = WordNetLemmatizer()
  test = []
  for i in text:
    test.append(stemmer.stem(i))
  return test

In [32]:
train_df['tweet_lemmatized'] = train_df['tweet_stemmed'].apply(stems)
test_df['tweet_lemmatized'] = test_df['tweet_stemmed'].apply(stems)
combine_df['tweet_lemmatized'] = combine_df['tweet_stemmed'].apply(stems)

In [33]:
train_df

,id,label,tweet,tweet_token,tweet_token_filtered,tweet_stemmed,tweet_lemmatized
0,1,0,when father is dysfunctional and is so selfish...,"[when, father, is, dysfunctional, and, is, so,...","[father, dysfunctional, selfish, drags, kids, ...","[father, dysfunct, selfish, drag, kid, dysfunc...","[father, dysfunct, selfish, drag, kid, dysfunc..."
1,2,0,thanks for lyft credit cannot use cause they d...,"[thanks, for, lyft, credit, can, not, use, cau...","[thanks, lyft, credit, use, cause, offer, whee...","[thank, lyft, credit, use, caus, offer, wheelc...","[thank, lyft, credit, use, cau, offer, wheelch..."
2,3,0,bihday your majesty,"[bihday, your, majesty]","[bihday, majesty]","[bihday, majesti]","[bihday, majesti]"
3,4,0,model love you take with you all the time in ur,"[model, love, you, take, with, you, all, the, ...","[model, love, take, time, ur]","[model, love, take, time, ur]","[model, love, take, time, ur]"
4,5,0,factsguide society now motivation,"[factsguide, society, now, motivation]","[factsguide, society, motivation]","[factsguid, societi, motiv]","[factsguid, societi, motiv]"
...,...,...,...,...,...,...,...
31957,31958,0,ate isz that youuu,"[ate, isz, that, youuu]","[ate, isz, youuu]","[ate, isz, youuu]","[ate, isz, youuu]"
31958,31959,0,to see nina turner on the airwaves trying to w...,"[to, see, nina, turner, on, the, airwaves, try...","[see, nina, turner, airwaves, trying, wrap, ma...","[see, nina, turner, airwav, tri, wrap, mantl, ...","[see, nina, turner, airwav, tri, wrap, mantl, ..."
31959,31960,0,listening to sad songs on monday morning otw t...,"[listening, to, sad, songs, on, monday, mornin...","[listening, sad, songs, monday, morning, otw, ...","[listen, sad, song, monday, morn, otw, work, sad]","[listen, sad, song, monday, morn, otw, work, sad]"
31960,31961,1,sikh temple vandalised in in calgary wso conde...,"[sikh, temple, vandalised, in, in, calgary, ws...","[sikh, temple, vandalised, calgary, wso, conde...","[sikh, templ, vandalis, calgari, wso, condemn,...","[sikh, templ, vandali, calgari, wso, condemn, ..."
31961,31962,0,thank you for you follow,"[thank, you, for, you, follow]","[thank, follow]","[thank, follow]","[thank, follow]"

In [34]:
test_df

,id,tweet,tweet_token,tweet_token_filtered,tweet_stemmed,tweet_lemmatized
0,31963,studiolife aislife requires passion dedication...,"[studiolife, aislife, requires, passion, dedic...","[studiolife, aislife, requires, passion, dedic...","[studiolif, aislif, requir, passion, dedic, wi...","[studiolif, aislif, requir, passion, dedic, wi..."
1,31964,white supremacists want everyone to see the ne...,"[white, supremacists, want, everyone, to, see,...","[white, supremacists, want, everyone, see, new...","[white, supremacist, want, everyon, see, new, ...","[white, supremacist, want, everyon, see, new, ..."
2,31965,safe ways to heal your acne altwaystoheal heal...,"[safe, ways, to, heal, your, acne, altwaystohe...","[safe, ways, heal, acne, altwaystoheal, health...","[safe, way, heal, acn, altwaystoh, healthi, heal]","[safe, way, heal, acn, altwaystoh, healthi, heal]"
3,31966,is the hp and the cursed child book up for res...,"[is, the, hp, and, the, cursed, child, book, u...","[hp, cursed, child, book, reservations, alread...","[hp, curs, child, book, reserv, alreadi, ye, h...","[hp, cur, child, book, reserv, alreadi, ye, ha..."
4,31967,rd bihday to my amazing hilarious nephew eli a...,"[rd, bihday, to, my, amazing, hilarious, nephe...","[rd, bihday, amazing, hilarious, nephew, eli, ...","[rd, bihday, amaz, hilari, nephew, eli, ahmir,...","[rd, bihday, amaz, hilari, nephew, eli, ahmir,..."
...,...,...,...,...,...,...
17192,49155,thought factory left right polarisation trump ...,"[thought, factory, left, right, polarisation, ...","[thought, factory, left, right, polarisation, ...","[thought, factori, left, right, polaris, trump...","[thought, factori, left, right, polari, trump,..."
17193,49156,feeling like mermaid hairflip neverready forma...,"[feeling, like, mermaid, hairflip, neverready,...","[feeling, like, mermaid, hairflip, neverready,...","[feel, like, mermaid, hairflip, neverreadi, fo...","[feel, like, mermaid, hairflip, neverreadi, fo..."
17194,49157,hillary campaigned today in ohio omg amp used ...,"[hillary, campaigned, today, in, ohio, omg, am...","[hillary, campaigned, today, ohio, omg, amp, u...","[hillari, campaign, today, ohio, omg, amp, use...","[hillari, campaign, today, ohio, omg, amp, use..."
17195,49158,happy at work conference right mindset leads t...,"[happy, at, work, conference, right, mindset, ...","[happy, work, conference, right, mindset, lead...","[happi, work, confer, right, mindset, lead, cu...","[happi, work, confer, right, mindset, lead, cu..."
17196,49159,my song so glad free download shoegaze newmusi...,"[my, song, so, glad, free, download, shoegaze,...","[song, glad, free, download, shoegaze, newmusi...","[song, glad, free, download, shoegaz, newmus, ...","[song, glad, free, download, shoegaz, newmu, n..."

In [35]:
combine_df

,id,label,tweet,tweet_token,tweet_token_filtered,tweet_stemmed,tweet_lemmatized
0,1,0.0,when father is dysfunctional and is so selfish...,"[when, father, is, dysfunctional, and, is, so,...","[father, dysfunctional, selfish, drags, kids, ...","[father, dysfunct, selfish, drag, kid, dysfunc...","[father, dysfunct, selfish, drag, kid, dysfunc..."
1,2,0.0,thanks for lyft credit cannot use cause they d...,"[thanks, for, lyft, credit, can, not, use, cau...","[thanks, lyft, credit, use, cause, offer, whee...","[thank, lyft, credit, use, caus, offer, wheelc...","[thank, lyft, credit, use, cau, offer, wheelch..."
2,3,0.0,bihday your majesty,"[bihday, your, majesty]","[bihday, majesty]","[bihday, majesti]","[bihday, majesti]"
3,4,0.0,model love you take with you all the time in ur,"[model, love, you, take, with, you, all, the, ...","[model, love, take, time, ur]","[model, love, take, time, ur]","[model, love, take, time, ur]"
4,5,0.0,factsguide society now motivation,"[factsguide, society, now, motivation]","[factsguide, society, motivation]","[factsguid, societi, motiv]","[factsguid, societi, motiv]"
...,...,...,...,...,...,...,...
49154,49155,NaN,thought factory left right polarisation trump ...,"[thought, factory, left, right, polarisation, ...","[thought, factory, left, right, polarisation, ...","[thought, factori, left, right, polaris, trump...","[thought, factori, left, right, polari, trump,..."
49155,49156,NaN,feeling like mermaid hairflip neverready forma...,"[feeling, like, mermaid, hairflip, neverready,...","[feeling, like, mermaid, hairflip, neverready,...","[feel, like, mermaid, hairflip, neverreadi, fo...","[feel, like, mermaid, hairflip, neverreadi, fo..."
49156,49157,NaN,hillary campaigned today in ohio omg amp used ...,"[hillary, campaigned, today, in, ohio, omg, am...","[hillary, campaigned, today, ohio, omg, amp, u...","[hillari, campaign, today, ohio, omg, amp, use...","[hillari, campaign, today, ohio, omg, amp, use..."
49157,49158,NaN,happy at work conference right mindset leads t...,"[happy, at, work, conference, right, mindset, ...","[happy, work, conference, right, mindset, lead...","[happi, work, confer, right, mindset, lead, cu...","[happi, work, confer, right, mindset, lead, cu..."
49158,49159,NaN,my song so glad free download shoegaze newmusi...,"[my, song, so, glad, free, download, shoegaze,...","[song, glad, free, download, shoegaze, newmusi...","[song, glad, free, download, shoegaz, newmus, ...","[song, glad, free, download, shoegaz, newmu, n..."

14. Сохраним результат предобработки в pickle-файл.

In [36]:
with open('data_train.pickle', 'wb') as f:
  pickle.dump(train_df, f)

In [37]:
with open('data_test.pickle', 'wb') as f:
  pickle.dump(test_df, f)

In [38]:
with open('data_combine.pickle', 'wb') as f:
  pickle.dump(combine_df, f)